# Generated by Django 4.1.7 on 2023-04-09 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0005_packageselfmanagement"),
        ("payments", "0003_payment_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="course",
        ),
        migrations.AddField(
            model_name="payment",
            name="package_self_management",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="packages.packageselfmanagement",
            ),
        ),
    ]
