# Generated by Django 3.2 on 2022-03-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscription",
            field=models.CharField(
                choices=[("basic", "Basico"), ("full", "Full")],
                default="basic",
                max_length=10,
            ),
        ),
    ]
