# Generated by Django 3.2 on 2022-03-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscription",
            field=models.CharField(
                choices=[("none", "Ninguno"), ("basic", "Basico"), ("full", "Full")],
                default="none",
                max_length=10,
            ),
        ),
    ]
