# Generated by Django 3.2 on 2022-06-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birth_date",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
