# Generated by Django 3.2 on 2022-07-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deferred_document_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deferred_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
