# Generated by Django 4.1.7 on 2023-03-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customuser_address_customuser_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
