# Generated by Django 4.1.7 on 2023-04-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_customuser_city_alter_customuser_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscription",
            field=models.CharField(
                blank=True,
                choices=[("none", "Ninguno"), ("basic", "Basico"), ("full", "Full")],
                default="none",
                max_length=10,
                null=True,
            ),
        ),
    ]
