# Generated by Django 4.1.7 on 2023-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_customuser_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[("admin", "Admin"), ("teacher", "Teacher"), ("user", "User")],
                default="user",
                max_length=10,
            ),
        ),
    ]
