# Generated by Django 3.2 on 2022-03-21 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_alter_comment_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="course",
            new_name="topic",
        ),
    ]
