# Generated by Django 3.2 on 2022-03-22 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_course_slug"),
        ("comments", "0004_rename_course_comment_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="courses.topic",
            ),
        ),
        migrations.AlterField(
            model_name="replycomment",
            name="comment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="comments.comment",
            ),
        ),
    ]
