# Generated by Django 3.2 on 2022-03-22 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_course_slug"),
        ("comments", "0005_auto_20220321_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="courses.topic",
            ),
        ),
    ]
