# Generated by Django 3.2 on 2022-03-22 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0006_alter_comment_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replycomment",
            name="comment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer",
                to="comments.comment",
            ),
        ),
    ]
