# Generated by Django 3.2 on 2022-03-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0007_alter_replycomment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_answered",
            field=models.BooleanField(default=False),
        ),
    ]
