# Generated by Django 3.2 on 2022-03-22 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0008_comment_is_answered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_answered",
        ),
    ]
