# Generated by Django 4.1.7 on 2023-03-05 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currencies",
                    models.CharField(
                        choices=[("EUR", "EUR"), ("USD", "USD")],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                (
                    "balance",
                    models.CharField(
                        choices=[
                            ("fifty_thousand", "FIFTY_THOUSAND"),
                            ("one_hundred_thousand", "ONE_HUNDRED_THOUSAND"),
                            ("two_hundred_thousand", "TWO_HUNDRED_THOUSAND"),
                            ("five_hundred_thousand", "FIVE_HUNDRED_THOUSAND"),
                        ],
                        default="fifty_thousand",
                        max_length=30,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("euro_street_basic", "EuroStreet Basic"),
                            ("euro_street_full", "EuroStreet Full"),
                        ],
                        default="euro_street_basic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("closed", "Closed"),
                            ("active", "Active"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", users.fields.LowerCaseEmailField(max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(blank=True, max_length=10)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("tos", models.BooleanField(default=False)),
                ("cancellation_policies", models.BooleanField(default=False)),
                ("end_date", models.DateTimeField()),
                ("login", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("password_investor", models.CharField(max_length=50)),
                ("server", models.CharField(max_length=50)),
                ("windows", models.CharField(max_length=50)),
                ("ios", models.CharField(max_length=50)),
                ("web", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
