# Generated by Django 4.1.7 on 2023-03-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="currencies",
            field=models.CharField(
                choices=[("eur", "EUR"), ("usd", "USD")], default="eur", max_length=3
            ),
        ),
    ]
