# Generated by Django 4.1.7 on 2023-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0002_alter_package_currencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="address",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
