# Generated by Django 4.1.7 on 2023-04-03 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0003_package_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="ios",
            new_name="mt_ios",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="login",
            new_name="mt_login",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="password",
            new_name="mt_password",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="password_investor",
            new_name="mt_password_investor",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="server",
            new_name="mt_server",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="web",
            new_name="mt_web",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="windows",
            new_name="mt_windows",
        ),
    ]
