# Generated by Django 4.1.7 on 2023-04-09 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0005_packageselfmanagement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={"verbose_name_plural": "Packages trader"},
        ),
        migrations.RenameField(
            model_name="packageselfmanagement",
            old_name="PACKAGE_type",
            new_name="package_type",
        ),
        migrations.AddField(
            model_name="packageselfmanagement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packageselfmanagement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
