# Generated by Django 4.1.7 on 2023-04-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0007_alter_packageselfmanagement_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("closed", "Closed"),
                    ("active", "Active"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="packageselfmanagement",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("closed", "Closed"),
                    ("active", "Active"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
