# Generated by Django 4.1.7 on 2023-05-03 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("packages", "0008_alter_package_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mt_login", models.CharField(max_length=50)),
                ("mt_password", models.CharField(max_length=50)),
                ("mt_password_investor", models.CharField(max_length=50)),
                ("mt_server", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_package",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
