# Generated by Django 4.1.7 on 2023-05-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0009_demopackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="demopackage",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="package",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="packageselfmanagement",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=3
            ),
        ),
    ]
