# Generated by Django 4.1.7 on 2023-05-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0010_demopackage_value_package_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="packageselfmanagement",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=4
            ),
        ),
    ]
