# Generated by Django 4.1.7 on 2023-05-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0011_alter_package_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="value",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name="packageselfmanagement",
            name="value",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
