# Generated by Django 4.1.7 on 2023-05-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0013_alter_demopackage_options_alter_package_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demopackage",
            name="account_type",
            field=models.CharField(default="Forex USD", max_length=50),
        ),
        migrations.AddField(
            model_name="demopackage",
            name="name",
            field=models.CharField(default="MetaTrader Web Demo", max_length=50),
        ),
    ]
