# Generated by Django 4.1.7 on 2023-05-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0014_demopackage_account_type_demopackage_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="demopackage",
            name="mt_leverage",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
