# Generated by Django 4.1.7 on 2023-05-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0016_alter_demopackage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageselfmanagement",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="packageselfmanagement",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="packageselfmanagement",
            name="postal_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
