# Generated by Django 4.1.7 on 2023-05-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0017_alter_packageselfmanagement_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="package",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="package",
            name="postal_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
