# Generated by Django 3.2 on 2022-02-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
