# Generated by Django 3.2 on 2022-05-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="video",
            field=models.CharField(default="Sin imagen", max_length=500),
        ),
    ]
