# Generated by Django 3.2 on 2022-05-09 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_topic_seen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="answers",
            new_name="questions",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="question",
        ),
    ]
