# Generated by Django 3.2 on 2022-05-10 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_auto_20220509_2241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="courses.course",
            ),
        ),
    ]
