# Generated by Django 3.2 on 2022-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_courseapprove"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("body", models.JSONField()),
            ],
        ),
    ]
