# Generated by Django 3.2 on 2022-05-22 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_seentopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="seentopic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
