# Generated by Django 3.2 on 2022-05-22 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_auto_20220522_2246"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seentopic",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RenameField(
            model_name="seentopic",
            old_name="topics",
            new_name="topic",
        ),
    ]
