# Generated by Django 3.2 on 2022-09-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_auto_20220522_2331"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseapprove",
            name="certificate",
            field=models.CharField(default="BLANK", max_length=200),
            preserve_default=False,
        ),
    ]
