# Generated by Django 3.2 on 2022-09-03 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_alter_courseapprove_certificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseapprove",
            old_name="certificate",
            new_name="certificate_url",
        ),
    ]
