from django.urls import path

from courses.views import (
    CertificateApproveView,
    CourseApproveView,
    CreateCategoryView,
    CreateCourseView,
    CreateModuleView,
    CreateQuizView,
    CreateSeenTopicView,
    CreateTopicView,
    DeleteCourseView,
    DeleteModuleView,
    DeleteQuizView,
    DeleteTopicView,
    ListAdminCoursesView,
    ListAdminMostViewedCoursesView,
    ListCategoryView,
    ListCoursesView,
    ListModuleView,
    ListMyCoursesApproveView,
    ListMyCoursesView,
    ListMyModulesView,
    ListMyQuizzesView,
    ListMyTopicsView,
    ListQuizzesView,
    ListSeenTopicsView,
    ListTopicsByModuleView,
    ListTopicView,
    PaymentBasic,
    PaymentFull,
    RetrieveCourseView,
    RetrieveModuleView,
    UpdateCategoryView,
    UpdateCourseView,
    UpdateModuleView,
    UpdateQuizView,
    UpdateTopicView,
)

urlpatterns = [
    path(
        "create/category/",
        CreateCategoryView.as_view(),
    ),
    # path("delete/category/<int:pk>/", DeleteCategoryView.as_view()),
    # path("retrieve/category/<int:pk>/", RetrieveCategoryView.as_view()),
    path(
        "update/category/<int:pk>/",
        UpdateCategoryView.as_view(),
    ),
    path(
        "list/categories/",
        ListCategoryView.as_view(),
    ),
    path(
        "create/course/",
        CreateCourseView.as_view(),
    ),
    path(
        "update/course/<int:pk>/",
        UpdateCourseView.as_view(),
    ),
    path(
        "retrieve/course/<int:pk>/",
        RetrieveCourseView.as_view(),
    ),
    path(
        "delete/course/<int:pk>/",
        DeleteCourseView.as_view(),
    ),
    path(
        "list/courses/",
        ListCoursesView.as_view(),
    ),
    path(
        "my/courses/",
        ListMyCoursesView.as_view(),
    ),
    path(
        "list/admin/courses/",
        ListAdminCoursesView.as_view(),
    ),
    path(
        "list/most/viewed/courses/",
        ListAdminMostViewedCoursesView.as_view(),
    ),
    path(
        "approve/course/",
        CourseApproveView.as_view(),
    ),
    path(
        "list/my/courses-approve/",
        ListMyCoursesApproveView.as_view(),
    ),
    path(
        "certificate/<int:course_id>/",
        CertificateApproveView.as_view(),
    ),
    path(
        "create/module/",
        CreateModuleView.as_view(),
    ),
    path(
        "delete/module/<int:pk>/",
        DeleteModuleView.as_view(),
    ),
    path(
        "update/module/<int:pk>/",
        UpdateModuleView.as_view(),
    ),
    path(
        "retrieve/module/<int:pk>/",
        RetrieveModuleView.as_view(),
    ),
    path(
        "list/modules/<int:pk>/",
        ListModuleView.as_view(),
    ),
    path(
        "my/modules/",
        ListMyModulesView.as_view(),
    ),
    path(
        "create/topic/",
        CreateTopicView.as_view(),
    ),
    path(
        "delete/topic/<int:pk>/",
        DeleteTopicView.as_view(),
    ),
    path(
        "update/topic/<int:pk>/",
        UpdateTopicView.as_view(),
    ),
    path(
        "detail/topics/<int:pk>/",
        ListTopicView.as_view(),
    ),
    path(
        "list/topics-by-module/<int:pk>/",
        ListTopicsByModuleView.as_view(),
    ),
    path(
        "my/topics/",
        ListMyTopicsView.as_view(),
    ),
    path(
        "seeing/topics/",
        ListSeenTopicsView.as_view(),
    ),
    path(
        "last-seen/topic/",
        CreateSeenTopicView.as_view(),
    ),
    path(
        "create/quiz/",
        CreateQuizView.as_view(),
    ),
    path(
        "delete/quiz/<int:pk>/",
        DeleteQuizView.as_view(),
    ),
    path(
        "update/quiz/<int:pk>/",
        UpdateQuizView.as_view(),
    ),
    path(
        "my/quizzes/",
        ListMyQuizzesView.as_view(),
    ),
    path(
        "list/quizzes/<int:pk>/",
        ListQuizzesView.as_view(),
    ),
    # path(
    #    "basic/payment/",
    #    PaymentBasic.as_view(),
    # ),
    path(
        "full/payment/",
        PaymentFull.as_view(),
    ),
]
